### ISSUE TITLE
If user links a contextid they've used before, update the timestamp

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#100]
Check that the BrightID is the same as the one previously linked. If so, update the timestamp and don't return an error.

**Comment by adamstallard** [comment]
This will help with an error that shows up in the apps tab and can't be removed. It also helps apps get the right

**Comment by abramsymons** [comment]
We don't return error on this anymore:
https://github.com/BrightID/BrightID-Node/blob/85d9e699d914af8c548531e96ec7b8c9ee2357c2/web_services/foxx/brightid5/db.js#L532-L535
But we don't update the `timestamp`
I think it's better to have the older timestamp there instead of renewing that, to be able to rely on that as time that link established.
