### ISSUE TITLE
Revoke SeedConnected verification by a seed reporting. 

### ISSUE THREAD

**Issue by siftal** [BrightID/BrightID-Node#170]
if a user has SeedConnected, and a seed flags that user as suspicious (for example) then it will remove their SeedConected status.

**Comment by adamstallard** [comment]
This could turn into a verification-revoking war between seed groups.  I could have my verification revoked because one person somewhere doesn't like me.

If you remember our first iteration of flagging, if two people flagged someone it would remove them from a group. It didn't remove their verification, it just removed them from the group. At the time, @abramsymons objected saying it gave individuals too much power over someone's verification.  Again, this required two flags and the user could always join another group to get their verification.

I'm willing to try this, but I wanted to remind you of the historical context of flagging other users and its relationship to verification.

**Comment by siftal** [comment]
We have a new plan to add a level to the seedConnected verification. Connecting to each seed group increases the level and reporting by a seed group decreases it.
For example, if a user has connected to 3 different seed its level will be 3, and if a member of a seed group report that user as suspicious (for example) then it will decrease the level by a multiplier (for example 2)
